version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile  
    ports:
     - "8050:8050"
    volumes:
      - .:/code
    environment: 
      - DASH_DEBUG="${DASH_DEBUG}"
    command: ["python3", "-u", "main.py"]



networks:
  default:
    external:
      name: targets_network
      